/*********Generated by contiki/tools/makefsdata on 2015-07-10*********/


const char data_PWD_EN[8]  = {
  /* /PWD_EN */
   0x2f, 0x50, 0x57, 0x44, 0x5f, 0x45, 0x4e, 0x00};

const char data_PWD[22]  = {
  /* /PWD */
   0x2f, 0x50, 0x57, 0x44, 0x00,
   0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30,
   0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x0a};


/* Structure of linked list (all offsets relative to start of section):*/
struct device_fsdata_file {
   const struct device_fsdata_file *next; //actual flash address of next link
   const char *name;                     //offset to coffee file name
   const char *data;                     //offset to coffee file data
   const int len;                        //length of file data
#if DEVICE_FS_STATISTICS == 1               //not enabled since list is in PROGMEM
   uint16_t count;                       //storage for file statistics
#endif
};

const struct device_fsdata_file          file_PWD_EN[] ={{                   0, data_PWD_EN        , data_PWD_EN         +8, sizeof(data_PWD_EN)          -8}};
const struct device_fsdata_file             file_PWD[] ={{         file_PWD_EN, data_PWD           , data_PWD            +5, sizeof(data_PWD)             -5}};

#define DEVICE_FS_ROOT  file_PWD
#define DEVICE_FS_NUMFILES  2
#define DEVICE_FS_SIZE 30
