/*
 *  Created by Jun Fang on 14-11-24.
 *  Copyright (c) 2014年 Jun Fang. All rights reserved.
 */

#ifndef _IPSO_OBJECT_H
#define _IPSO_OBJECT_H

/*IPSO object define*/
#define IPSO_OBJECT_DIGITAL_INPUT        3200
#define IPSO_OBJECT_DIGITAL_OUTPUT       3201
#define IPSO_OBJECT_ANALOGUE_INPUT       3202
#define IPSO_OBJECT_ANALOGUE_OUTPUT      3203
#define IPSO_OBJECT_GENERIC_SENSOR       3300
#define IPSO_OBJECT_ILLUMINANCE_SENSOR   3301
#define IPSO_OBJECT_PRESENCE_SENSOR      3302
#define IPSO_OBJECT_TEMPERATURE_SENSOR   3303
#define IPSO_OBJECT_HUMIDITY_SENSOR      3304
#define IPSO_OBJECT_POWER_MEASUREMENT    3305
#define IPSO_OBJECT_ACTUATION            3306
#define IPSO_OBJECT_SET_POINT            3308
#define IPSO_OBJECT_LOAD_CONTROL         3310
#define IPSO_OBJECT_LIGHT_CONTROL        3311
#define IPSO_OBJECT_POWER_CONTROL        3312
#define IPSO_OBJECT_ACCELEROMETER        3313
#define IPSO_OBJECT_MAGNETOMETER         3314
#define IPSO_OBJECT_BAROMETER            3315

#endif
